### ISSUE TITLE
Bug in combination with UIActivityViewController

### ISSUE THREAD

**Issue by justvanbloom** [davbeck/TNKRefreshControl#1]
Stange bug with UIActivityViewController. If tnkrefresh is on view and you open a UIActivityViewController, nothing goes anymore. I think its in combination with layer errors from CKShapeView.m highlited by xcode. Found no way to fix it. Any thoughts?

**Comment by davbeck** [comment]
I believe that this is the same issue from [CKShapeView](https://github.com/conradev/CKShapeView/pull/5).

As soon as that pull request is included in a pod release I will update the podspec for this project. Until then, you can add the following to your own Podfile to get the fix:

```
pod 'CKShapeView', git: 'https://github.com/davbeck/CKShapeView.git', commit: '822f6a4693c014ff491d8e72fdc2e07c25bcaa82'
```
